#Config file for Ipython_HistoryManager
#https://github.com/LGregg-Allured/IPython-History-Manager

path = "/home/user/.ipython/profile" #path to default profile directory

#python modules to be auto imported
modules = ["os", "scipy","matplotlib.pyplot"]

#variables to be auto loaded (such as scientific constants)
[variables]
pi = 3.14159
e = 1.6e-19