#Config file for Ipython_HistoryManager
#https://github.com/LGregg-Allured/IPython-History-Manager
#Version: 0.2.1

path = "/home/user/.ipython/profile" #path to default profile directory

#variables to be auto loaded (such as scientific constants)
[variables]
pi = 3.14159
e = 1.6e-19